swagger: "2.0"
info:
  description: needs to add a description
  title: An Itineraries server application
  version: 1.0.0
schemes:
- http
#- https
paths:
  /live:
    get:
      tags:
      - liveness
      responses:
        200:
          description: liveness probe
        503:
          description: if not alive
          schema:
            $ref: "../../storage/swagger/swagger.yaml#/definitions/error"
        default:
          description: generic error response
          schema:
            $ref: "../../storage/swagger/swagger.yaml#/definitions/error"
  /ready:
    get:
      tags:
      - readiness
      responses:
        200:
          description: readiness probe
        503:
          description: if not ready
          schema:
            $ref: "../../storage/swagger/swagger.yaml#/definitions/error"
        default:
          description: generic error response
          schema:
            $ref: "../../storage/swagger/swagger.yaml#/definitions/error" 
  /itineraries:
    get:
      tags:
        - itineraries
      produces:
        - application/json
      parameters:
        - name: from
          in: query
          type: string
        - name: to
          in: query
          type: string
      responses:
        200:
          description: list of itineraries
          schema:
            type: array
            items:
              $ref: "#/definitions/itinerary"
        400:
          description: generic error response
          schema:
            $ref: "../../storage/swagger/swagger.yaml#/definitions/error"
        404:
          description: not found
          schema:
            $ref: "../../storage/swagger/swagger.yaml#/definitions/error"
        default:
          description: generic error response
          schema:
            $ref: "../../storage/swagger/swagger.yaml#/definitions/error"
definitions:
  itinerary:
    type: object
    properties:
      ItineraryID:
        type: string
      Description:
        type: string
      Segments:
        type: array
        items:
          $ref: "#/definitions/segment"
        readOnly: true
  segment: 
    type: object
    properties:
      SegmentID:
        type: integer
        format: int64
      Origin: 
        type: string
      Destination:
        type: string
      FlightNumber:
        type: string
      OperatingCarrier:
        type: string
      DepartureTime:
        type: string
      DepartureDate:
        type: string
      ArrivalTime:
        type: string
      ArrivalDate:
        type: string
      ArriveNextDay:
        type: boolean
